# react-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: docker.io/library/ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
